### ISSUE TITLE
Get error when building

### ISSUE THREAD

**Issue by nikitavoloboev** [ry/v8worker2#7]
I have Python 3 installed on my system.

```bash
~/go/src/github.com/ry/v8worker2
❯ ./build.py --use_ccache
out_path None
Rebuilding V8
Fetching dependencies.
depot_tools update failed. Conflict in /Users/nikivi/go/src/github.com/ry/v8worker2/depot_tools
/Users/nikivi/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:56: trailing whitespace.

/Users/nikivi/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:71: trailing whitespace.

/Users/nikivi/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:73: trailing whitespace.
Windows only).
/Users/nikivi/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:77: trailing whitespace.

/Users/nikivi/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:225: trailing whitespace.

warning: squelched 596 whitespace errors
warning: 601 lines add whitespace errors.
error: Failed to merge in the changes.
Patch failed at 0001 Create the Next Generation of depot_tools. Eh.
The copy of the patch that failed is found in: /Users/nikivi/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Running gn
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.
Traceback (most recent call last):
  File "./build.py", line 149, in <module>
    main()
  File "./build.py", line 85, in main
    lib_fn = Rebuild()
  File "./build.py", line 114, in Rebuild
    env=env)
  File "/nix/store/10f4qxb00wk9j6cicd9h1qzwqgnc36ji-python-2.7.14/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/nikivi/go/src/github.com/ry/v8worker2/depot_tools/gn', 'gen', '/Users/nikivi/go/src/github.com/ry/v8worker2/out/v8build', '--args=   is_component_build=false   is_debug=false   libcpp_is_static=false   symbol_level=1   treat_warnings_as_errors=false   use_custom_libcxx=false   use_sysroot=false   v8_deprecation_warnings=false   v8_embedder_string="-v8worker2"   v8_enable_gdbjit=false   v8_enable_i18n_support=false   v8_enable_test_features=false   v8_experimental_extra_library_files=[]   v8_extra_library_files=[]   v8_imminent_deprecation_warnings=false   v8_monolithic=true   v8_static_library=false   v8_target_cpu="x64"   v8_untrusted_code_mitigations=false   v8_use_external_startup_data=false   v8_use_snapshot=true  cc_wrapper="/Users/nikivi/.nix-profile/bin/ccache"']' returned non-zero exit status 1
```

**Comment by nikitavoloboev** [comment]
Also`/Users/nikivi/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/` dir is empty for me.

**Comment by xywf221** [comment]
I met this problem, too.

**Comment by xywf221** [comment]
You can get from here  [https://storage.googleapis.com/chrome-infra/depot_tools.zip](url)  replace depot_tools

**Comment by maxmcd** [comment]
As a heavy-handed solution, this should ensure you have all the files you need
```
git clone https://github.com/ry/v8worker2.git . \
    && rm -rf v8 \
    && git clone https://github.com/v8/v8.git && cd v8 \
    && cd .. \
    && rm -rf depot_tools \
    && git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git \
    && git submodule update --init --recursive
```
